# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 798c7c43378717a516c2ded05d079acaebbf320e7fd8c42554e4e10fd16caffab812b9ad573f659838edfbb8217d474a032eeba77308a6e025a631083ef51edd

test:
  secret_key_base: 7a6533dcc028e88a1cbc98a4d5eed0f3c4a5029c3b0ea5151d700a48f81f5b9becea43ea570b5212e061039f72751de20994853f5c1bd6f915919d4de78bf965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
